#pragma once

#include "platform/gen2_arch_common/port_mapping_config.h"  // for Gen2ArchNicsDeviceSingleConfig

// clang-format off

extern const Gen2ArchNicsDeviceSingleConfig g_hls2pcie_card_location_0_mapping;
extern const Gen2ArchNicsDeviceSingleConfig g_hls2pcie_card_location_1_mapping;
extern const Gen2ArchNicsDeviceSingleConfig g_hls2pcie_card_location_2_mapping;
extern const Gen2ArchNicsDeviceSingleConfig g_hls2pcie_card_location_3_mapping;
extern const Gen2ArchNicsDeviceSingleConfig g_hls2pcie_card_location_4_mapping;
extern const Gen2ArchNicsDeviceSingleConfig g_hls2pcie_card_location_5_mapping;
extern const Gen2ArchNicsDeviceSingleConfig g_hls2pcie_card_location_6_mapping;
extern const Gen2ArchNicsDeviceSingleConfig g_hls2pcie_card_location_7_mapping;

// clang-format on