/* SPDX-License-Identifier: MIT
 *
 * Copyright 2020 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */
#ifndef __GAUDI3_ARC_STM_H__
#define __GAUDI3_ARC_STM_H__

#include "gaudi3_arc_common_packets.h"

/**
 * \file    gaudi3_arc_stm.h
 * \brief   TRACE CPU IDs for each ARC CPUs
 *          The TRACE CPU ID should be used when emmiting a trace message
 *          over global STM.
 *          The TRACE CPU IDs are arranged sequentialy such that all ARCS
 *          of die 0 are first and then die 1 ARCS in the same order.
 */
enum {
	/* DIE 0 Scheduler ARCs */
	TRACE_CPU_ID_SCHED_ARC0  = 0, /* HD0_FARM_ARC0 */
	TRACE_CPU_ID_SCHED_ARC1  = 1, /* HD0_FARM_ARC1 */
	TRACE_CPU_ID_SCHED_ARC2  = 2, /* HD1_FARM_ARC0 */
	TRACE_CPU_ID_SCHED_ARC3  = 3, /* HD1_FARM_ARC1 */
	TRACE_CPU_ID_SCHED_ARC4  = 4, /* HD2_FARM_ARC0 */
	TRACE_CPU_ID_SCHED_ARC5  = 5, /* HD2_FARM_ARC1 */
	TRACE_CPU_ID_SCHED_ARC6  = 6, /* HD3_FARM_ARC0 */
	TRACE_CPU_ID_SCHED_ARC7 = 7, /* HD3_FARM_ARC1 */


	/* DIE 0 Engines */
	TRACE_CPU_ID_TPC_QMAN_ARC0 = 8, /* HD0_TPC0 */
	TRACE_CPU_ID_TPC_QMAN_ARC1 = 9, /* HD0_TPC1 */
	TRACE_CPU_ID_TPC_QMAN_ARC2 = 10, /* HD0_TPC2 */
	TRACE_CPU_ID_TPC_QMAN_ARC3 = 11, /* HD0_TPC3 */
	TRACE_CPU_ID_TPC_QMAN_ARC4 = 12, /* HD0_TPC4 */
	TRACE_CPU_ID_TPC_QMAN_ARC5 = 13, /* HD0_TPC5 */
	TRACE_CPU_ID_TPC_QMAN_ARC6 = 14, /* HD0_TPC6 */
	TRACE_CPU_ID_TPC_QMAN_ARC7 = 15, /* HD0_TPC7 */
	TRACE_CPU_ID_TPC_QMAN_ARC8 = 16, /* HD1_TPC0 */
	TRACE_CPU_ID_TPC_QMAN_ARC9 = 17, /* HD1_TPC1 */
	TRACE_CPU_ID_TPC_QMAN_ARC10 = 18, /* HD1_TPC2 */
	TRACE_CPU_ID_TPC_QMAN_ARC11 = 19, /* HD1_TPC3 */
	TRACE_CPU_ID_TPC_QMAN_ARC12 = 20, /* HD1_TPC4 */
	TRACE_CPU_ID_TPC_QMAN_ARC13 = 21, /* HD1_TPC5 */
	TRACE_CPU_ID_TPC_QMAN_ARC14 = 22, /* HD1_TPC6 */
	TRACE_CPU_ID_TPC_QMAN_ARC15 = 23, /* HD1_TPC7 */
	TRACE_CPU_ID_TPC_QMAN_ARC16 = 24, /* HD2_TPC0 */
	TRACE_CPU_ID_TPC_QMAN_ARC17 = 25, /* HD2_TPC1 */
	TRACE_CPU_ID_TPC_QMAN_ARC18 = 26, /* HD2_TPC2 */
	TRACE_CPU_ID_TPC_QMAN_ARC19 = 27, /* HD2_TPC3 */
	TRACE_CPU_ID_TPC_QMAN_ARC20 = 28, /* HD2_TPC4 */
	TRACE_CPU_ID_TPC_QMAN_ARC21 = 29, /* HD2_TPC5 */
	TRACE_CPU_ID_TPC_QMAN_ARC22 = 30, /* HD2_TPC6 */
	TRACE_CPU_ID_TPC_QMAN_ARC23 = 31, /* HD2_TPC7 */
	TRACE_CPU_ID_TPC_QMAN_ARC24 = 32, /* HD3_TPC0 */
	TRACE_CPU_ID_TPC_QMAN_ARC25 = 33, /* HD3_TPC1 */
	TRACE_CPU_ID_TPC_QMAN_ARC26 = 34, /* HD3_TPC2 */
	TRACE_CPU_ID_TPC_QMAN_ARC27 = 35, /* HD3_TPC3 */
	TRACE_CPU_ID_TPC_QMAN_ARC28 = 36, /* HD3_TPC4 */
	TRACE_CPU_ID_TPC_QMAN_ARC29 = 37, /* HD3_TPC5 */
	TRACE_CPU_ID_TPC_QMAN_ARC30 = 38, /* HD3_TPC6 */
	TRACE_CPU_ID_TPC_QMAN_ARC31 = 39, /* HD3_TPC7 */
	TRACE_CPU_ID_TPC_QMAN_ARC64 = 40, /* HD0_TPC8 */
	TRACE_CPU_ID_TPC_QMAN_ARC65 = 41, /* HD2_TPC8 */

	TRACE_CPU_ID_MME_QMAN_ARC0  = 42, /* HD0_MME */
	TRACE_CPU_ID_MME_QMAN_ARC1  = 43, /* HD1_MME */
	TRACE_CPU_ID_MME_QMAN_ARC2  = 44, /* HD2_MME */
	TRACE_CPU_ID_MME_QMAN_ARC3  = 45, /* HD3_MME */

	TRACE_CPU_ID_EDMA_QMAN_ARC0 = 46, /* HD1_EDMA0 */
	TRACE_CPU_ID_EDMA_QMAN_ARC1 = 47, /* HD1_EDMA1 */
	TRACE_CPU_ID_EDMA_QMAN_ARC2 = 48, /* HD3_EDMA0 */
	TRACE_CPU_ID_EDMA_QMAN_ARC3 = 49, /* HD3_EDMA1 */

	TRACE_CPU_ID_ROT_QMAN_ARC0  = 50,/* HD1_ROT0 */
	TRACE_CPU_ID_ROT_QMAN_ARC1  = 51,/* HD1_ROT1 */
	TRACE_CPU_ID_ROT_QMAN_ARC2  = 52,/* HD3_ROT0 */
	TRACE_CPU_ID_ROT_QMAN_ARC3  = 53,/* HD3_ROT1 */

	TRACE_CPU_ID_NIC_QMAN_ARC0  = 54, /* D0_NIC0 */
	TRACE_CPU_ID_NIC_QMAN_ARC1  = 55, /* D0_NIC1 */
	TRACE_CPU_ID_NIC_QMAN_ARC2  = 56, /* D0_NIC2 */
	TRACE_CPU_ID_NIC_QMAN_ARC3  = 57, /* D0_NIC3 */
	TRACE_CPU_ID_NIC_QMAN_ARC4  = 58, /* D0_NIC4 */
	TRACE_CPU_ID_NIC_QMAN_ARC5  = 59, /* D0_NIC5 */

	TRACE_CPU_ID_DIE0_MAX = 60,
	TRACE_CPU_ID_DIE0_SCHED_MAX = 8,

	/* DIE 1 Scheduler ARCs */
	TRACE_CPU_ID_SCHED_ARC8 = 0, /* HD4_FARM_ARC0 */
	TRACE_CPU_ID_SCHED_ARC9 = 1, /* HD4_FARM_ARC1 */
	TRACE_CPU_ID_SCHED_ARC10 = 2, /* HD5_FARM_ARC0 */
	TRACE_CPU_ID_SCHED_ARC11 = 3, /* HD5_FARM_ARC1 */
	TRACE_CPU_ID_SCHED_ARC12 = 4, /* HD6_FARM_ARC0 */
	TRACE_CPU_ID_SCHED_ARC13 = 5, /* HD6_FARM_ARC1 */
	TRACE_CPU_ID_SCHED_ARC14 = 6, /* HD7_FARM_ARC0 */
	TRACE_CPU_ID_SCHED_ARC15 = 7, /* HD7_FARM_ARC1 */

	/* DIE 1 Engines */
	TRACE_CPU_ID_TPC_QMAN_ARC32 = 8, /* HD4_TPC0 */
	TRACE_CPU_ID_TPC_QMAN_ARC33 = 9, /* HD4_TPC1 */
	TRACE_CPU_ID_TPC_QMAN_ARC34 = 10, /* HD4_TPC2 */
	TRACE_CPU_ID_TPC_QMAN_ARC35 = 11, /* HD4_TPC3 */
	TRACE_CPU_ID_TPC_QMAN_ARC36 = 12, /* HD4_TPC4 */
	TRACE_CPU_ID_TPC_QMAN_ARC37 = 13, /* HD4_TPC5 */
	TRACE_CPU_ID_TPC_QMAN_ARC38 = 14, /* HD4_TPC6 */
	TRACE_CPU_ID_TPC_QMAN_ARC39 = 15, /* HD4_TPC7 */
	TRACE_CPU_ID_TPC_QMAN_ARC40 = 16, /* HD5_TPC0 */
	TRACE_CPU_ID_TPC_QMAN_ARC41 = 17, /* HD5_TPC1 */
	TRACE_CPU_ID_TPC_QMAN_ARC42 = 18, /* HD5_TPC2 */
	TRACE_CPU_ID_TPC_QMAN_ARC43 = 19, /* HD5_TPC3 */
	TRACE_CPU_ID_TPC_QMAN_ARC44 = 20, /* HD5_TPC4 */
	TRACE_CPU_ID_TPC_QMAN_ARC45 = 21, /* HD5_TPC5 */
	TRACE_CPU_ID_TPC_QMAN_ARC46 = 22, /* HD5_TPC6 */
	TRACE_CPU_ID_TPC_QMAN_ARC47 = 23, /* HD5_TPC7 */
	TRACE_CPU_ID_TPC_QMAN_ARC48 = 24, /* HD6_TPC0 */
	TRACE_CPU_ID_TPC_QMAN_ARC49 = 25, /* HD6_TPC1 */
	TRACE_CPU_ID_TPC_QMAN_ARC50 = 26, /* HD6_TPC2 */
	TRACE_CPU_ID_TPC_QMAN_ARC51 = 27, /* HD6_TPC3 */
	TRACE_CPU_ID_TPC_QMAN_ARC52 = 28, /* HD6_TPC4 */
	TRACE_CPU_ID_TPC_QMAN_ARC53 = 29, /* HD6_TPC5 */
	TRACE_CPU_ID_TPC_QMAN_ARC54 = 30, /* HD6_TPC6 */
	TRACE_CPU_ID_TPC_QMAN_ARC55 = 31, /* HD6_TPC7 */
	TRACE_CPU_ID_TPC_QMAN_ARC56 = 32, /* HD7_TPC0 */
	TRACE_CPU_ID_TPC_QMAN_ARC57 = 33, /* HD7_TPC1 */
	TRACE_CPU_ID_TPC_QMAN_ARC58 = 34, /* HD7_TPC2 */
	TRACE_CPU_ID_TPC_QMAN_ARC59 = 35, /* HD7_TPC3 */
	TRACE_CPU_ID_TPC_QMAN_ARC60 = 36, /* HD7_TPC4 */
	TRACE_CPU_ID_TPC_QMAN_ARC61 = 37, /* HD7_TPC5 */
	TRACE_CPU_ID_TPC_QMAN_ARC62 = 38, /* HD7_TPC6 */
	TRACE_CPU_ID_TPC_QMAN_ARC63 = 39, /* HD7_TPC7 */
	TRACE_CPU_ID_TPC_QMAN_ARC66 = 40, /* HD5_TPC8 */
	TRACE_CPU_ID_TPC_QMAN_ARC67 = 41, /* HD7_TPC8 */

	TRACE_CPU_ID_MME_QMAN_ARC4  = 42, /* HD4_MME */
	TRACE_CPU_ID_MME_QMAN_ARC5  = 43, /* HD5_MME */
	TRACE_CPU_ID_MME_QMAN_ARC6  = 44, /* HD6_MME */
	TRACE_CPU_ID_MME_QMAN_ARC7  = 45, /* HD7_MME */

	TRACE_CPU_ID_EDMA_QMAN_ARC4 = 46, /* HD4_EDMA0 */
	TRACE_CPU_ID_EDMA_QMAN_ARC5 = 47, /* HD4_EDMA1 */
	TRACE_CPU_ID_EDMA_QMAN_ARC6 = 48, /* HD6_EDMA0 */
	TRACE_CPU_ID_EDMA_QMAN_ARC7 = 49, /* HD6_EDMA1 */

	TRACE_CPU_ID_ROT_QMAN_ARC4  = 50,/* HD4_ROT0 */
	TRACE_CPU_ID_ROT_QMAN_ARC5  = 51,/* HD4_ROT1 */
	TRACE_CPU_ID_ROT_QMAN_ARC6  = 52,/* HD6_ROT0 */
	TRACE_CPU_ID_ROT_QMAN_ARC7  = 53,/* HD6_ROT1 */

	TRACE_CPU_ID_NIC_QMAN_ARC6  = 54, /* D1_NIC0 */
	TRACE_CPU_ID_NIC_QMAN_ARC7  = 55, /* D1_NIC1 */
	TRACE_CPU_ID_NIC_QMAN_ARC8  = 56, /* D1_NIC2 */
	TRACE_CPU_ID_NIC_QMAN_ARC9  = 57, /* D1_NIC3 */
	TRACE_CPU_ID_NIC_QMAN_ARC10 = 58, /* D1_NIC4 */
	TRACE_CPU_ID_NIC_QMAN_ARC11 = 59, /* D1_NIC5 */
};

/**
 * Scheduler command events
 */
#define SCHED_STREAM_CMD_EVENT_ID	0
#define SCHED_DCCM_Q_CMD_EVENT_ID	1

/**
 * Scheduler DCCM Q events
 */
#define SCHED_DCCM_Q_EVENT_ID		0

/**
 * Scheduler instant events
 */
#define SCHED_INSTANT_EVENT_TYPE_ID		0
#define SCHED_INSTANT_EVENT_VALUE_ID	1
#define SCHED_INSTANT_EVENT_VALUE_SCHED_TYPE	2
#define SCHED_INSTANT_EVENT_VALUE_DISCARD_MCID	3

enum sched_instant_events_t {
    SCHED_INST_EVENT_CPU_ID = 0,
    SCHED_INST_EVENT_OPCODE = 1,
    SCHED_INST_EVENT_COLLECT_TIMESTAMP = 2,
    SCHED_INST_EVENT_COUNT = 3
};

/**
 * Engine sub command events
 */
#define ENG_SUB_CMD_EVENT_ID		0

/**
 * Engine instant events
 */
#define ENG_INSTANT_EVENT_TYPE_ID		0
#define ENG_INSTANT_EVENT_VALUE_ID		1
#define ENG_INSTANT_EVENT_VALUE_ENG_TYPE	2

enum eng_compute_instant_events_t {
    ENG_CMPT_INST_EVENT_CPU_ID = 0,
    ENG_CMPT_INST_EVENT_DYN_LIST_SIZE = 1,
    ENG_CMPT_INST_EVENT_STATIC_LIST_SIZE = 2,
    ENG_CMPT_INST_EVENT_STATIC_SCHED_DMA_WAIT_START = 3,
    ENG_CMPT_INST_EVENT_STATIC_SCHED_DMA_WAIT_END = 4,
    ENG_CMPT_INST_EVENT_STATIC_CQ_WAIT_START = 5,
    ENG_CMPT_INST_EVENT_STATIC_CQ_WAIT_END = 6,
    ENG_CMPT_INST_EVENT_STATIC_CQ_FULL = 7,
    ENG_CMPT_INST_EVENT_DYN_CQ_FULL = 8,
    ENG_CMPT_INST_EVENT_COUNT = 9
};

/**
 * encoding for scheduler stream payload
 */
#define SCHED_STM_STREAM_PAYLOAD(stream_id, sched_type) \
	(((sched_type & 0x1F) << 6) | (stream_id & 0x3F))

#define SCHED_STM_INSTANT_EVENT_PAYLOAD(evt, val) \
	(((val & 0xFFFF) << 16) | (evt & 0xFFFF))

#define SCHED_STM_PAYLOAD_TO_STREAM_ID(payload) \
    ((payload) & 0x3F)

#define SCHED_STM_PAYLOAD_TO_SCHED_TYPE(payload) \
    (((payload) >> 6) & 0x1F)

#define SCHED_STM_PAYLOAD_TO_VAL(payload) \
    (((payload) >> 16) & 0xFFFF)

#define SCHED_STM_PAYLOAD_TO_EVENT_ID(payload) \
    ((payload) & 0xFFFF)

/**
 * encoding for engine command payload
 */
#define ENG_STM_CMD_PAYLOAD(dccm_q_id, eng_type) \
	(((eng_type & 0x1F) << 3) | (dccm_q_id & 0x7))

#define ENG_STM_PAYLOAD_TO_DCCM_Q_ID(payload) \
    ((payload) & 0x7)

#define ENG_STM_PAYLOAD_TO_ENG_TYPE(payload) \
    (((payload) >> 3) & 0x1F)

#define ENG_STM_PAYLOAD_TO_VAL(payload) \
    (((payload) >> 16) & 0xFFFF)

#define ENG_STM_PAYLOAD_TO_EVENT_ID(payload) \
    ((payload) & 0xFFFF)

#endif /* __GAUDI3_ARC_STM_H__ */
